# Copyright 2024 @x-coconut
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:

  keycloak:
    build:
      context: .
      dockerfile: keycloak_dockerfile 
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8433"
    environment:
      KEYCLOAK_ADMIN: admin # UPDATE USERNAME
      KEYCLOAK_ADMIN_PASSWORD: admin # UPDATE PASSWORD
      DB_VENDOR: POSTGRES
      DB_ADDR: 172.2.0.3
      DB_PORT: 5432
      DB_DATABASE: keycloakDB
      DB_USER: user # UPDATE USERNAME
      DB_PASSWORD: password # UPDATE PASSWORD
      KEYCLOAK_TLS_KEYSTORE: /opt/keycloak/conf/keycloak.jks
      KEYCLOAK_TLS_KEYSTORE_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      internal_1:
        ipv4_address: 172.1.0.2
      internal_2:
        ipv4_address: 172.2.0.2
    depends_on: # ensure postgres DB exists first
      - postgres
      - python_server
    
  rabbitmq:
    image: rabbitmq:management # enable management plugin 
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest # UPDATE USERNAME
      RABBITMQ_DEFAULT_PASS: guest # UPDATE PASSWORD
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      internal_1:
        ipv4_address: 172.1.0.3
      internal_3:
        ipv4_address: 172.3.0.3
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user # UPDATE USERNAME
      POSTGRES_PASSWORD: password # UPDATE PASSWORD
      POSTGRES_DB: keycloakDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      internal_2:
        ipv4_address: 172.2.0.3

  python_server:
    build:
      context: .
      dockerfile: server_dockerfile
    container_name: python_server
    environment:
      KEY_PATH: /mnt/ECC_private_key.txt
    volumes:
      - key_data:/mnt
    network_mode: "host"

  python_wrapper:
    build:
      context: .
      dockerfile: wrapper_dockerfile
    container_name: python_wrapper
    environment:
      KEY_PATH: /mnt/ECC_private_key.txt
    volumes:
      - key_data:/mnt
    networks:
      internal_3:
        ipv4_address: 172.3.0.2
      external_1:
        ipv4_address: 172.11.0.2
    depends_on: # ensure RabbitMQ, python_server containers started before python_wrapper
      rabbitmq:
        condition: service_healthy
      python_server:
        condition: service_started

networks:
  internal_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/16
    internal: true 

  internal_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/16
    internal: true 

  internal_3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16
    internal: true

  external_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16
    internal: false  

volumes:
  keycloak_data:
  rabbitmq_data:
  postgres_data:
  key_data:
